### ISSUE TITLE
Deciding what kind of site the community site would be built on

### ISSUE THREAD

**Issue by gbozee** [pyung/pyung.github.io#11]
We would need to decide what kind of site it would be.

The options are 

1. A pure static site that can easily be hosted for free.

2. A dynamic site that would require being built with a backend web framework

Here are Some pros for building as a static site.
**Pros**
1. It is very easy to deploy and deployment options are almost close to 0. Since the site would be running all year long and not just for a particular duration like the Pycon site, this is something to really consider.
2. Since most of the external pages are static pages, it would be extremely fast to load. Also deployment on file change is near instantenous

**Cons**
1. We would have to rely on using a Javascript framework if we are going to have any form of dynamism e.g User authentication, Protected routes (We could solve this by building an api only backend that is deployed on heroku)

For building with a Dynamic site
**Pro**
1. We are free to build using any popular python web framework with all the inbuilt libraries  and we get free authentication and large reusable libraries that can handle most of the tasks we want

**Con**
1. Extra maintanance overhead involved when deploying
2. More expensive to deploy. We could use heroku but we would easily max out the free plan because of the large number.
3. Deployed pages even if static are slower and we are at the wimp of Heroku which on occasion put servers to sleep if running on the free plan. To avoid this, we would either need to move to a paid plan which is expensive in the long term or host  our application on a dedicated VPS which goes back to the Point 1 i made.

**Comment by gbozee** [comment]
@shante66 @ichux  Sorry for pulling you to this discussion but its something we would need to agree on

**Comment by gbozee** [comment]
I would vote for making it a static site. Most of the Cons can be easily resolved. Having to not deal with deployment/devops related tasks is something I personally strive for. 

Please @pyung/development-team voice your suggestions.

**Comment by Olamyy** [comment]
I'd vote for making it a dynamic site. It might take a bit longer and a bit more work but it'd help bring as much interactivity into the site as possible.
A static site would be pretty boring in my opinion.

**Comment by jattoabdul** [comment]
Not necessarily, i don't think it would be boring @Olamyy. With good design, architecture and flexible frontend framework, we could achieve a well interactive but static website with little dynamism as @gbozee said. I think i support making it static also, if we think about everything @gbozee said properly, especially the extra maintenance overhead that the other option will pose to us.

**Comment by gbozee** [comment]
@olamyy the static site won't be boring at all. In fact it would be much fun to build than if it were dynamic. What I mean by static is at the end of the day, we are just deploying raw HTML and CSS and JavaScript. We would be making use of static generator framework s and they don't have to be in python. Also, we are likely to end up completely decoupling the frontend from d back end with a static site approach

**Comment by adekoder** [comment]
i feel it depends on the features that will be on the site that will determine either full static or full dynamic or both

**Comment by gbozee** [comment]
The features of what the site would contain are listed here 
https://github.com/orgs/pyung/teams/development-team/discussions/2

**Comment by gbozee** [comment]
We can't go wrong with whatever approach we take. Both the static approach and the dynamic approach can handle whatever we throw at it.

**Comment by gbozee** [comment]
We would be building something that closely resembles https://djangogirls.org/ 

It would consist of the following

1. A blog

2. A store 

3. An events page (A place to find information about all python events happening in the country)

Most of what django girls have, we might end up replicating it.

From a static point of view, we won't need to maintain a database of the blogs or the events. As for the store, We could use Heroku free pricing to host the inventory. The database would only be concerned with saving User mailing list info,  inventory data. So in a way would still use a backend framework for this but it would only end up rendering json which the static site would consume.

We would be able to easily move the backend without disrupting the user facing part of the web application when heroku no longer becomes an option for hosting the api.

**Comment by adekoder** [comment]
I see the point you are making here , we build the three features separate and all are connect together , if am right

**Comment by gbozee** [comment]
Well in a way you are right @adekoder . But the store implementation is the only one that is drastically different.

**Comment by adekoder** [comment]
That means we are working with a REST architectural pattern

**Comment by gbozee** [comment]
Yeah if what you meant is using Web API's (ajax, json etc)

**Comment by depecode** [comment]
I will recommend going with the static files first, because of the expensive of hosting the dynamic site

**Comment by yemisi-o** [comment]
I would say dynamic, but with your explanation of how the store will be implemented above, we can go with 'static' since there will still be a sort of backend.

**Comment by teenoh** [comment]
I'll go with static site, that'll be better

**Comment by gbozee** [comment]
So work begins now.

To members of the Backend Team, Here are the tasks that you currently would be embarking on
1. Implementing a rest api for Events like this https://djangogirls.org/events/
2. Implementing a rest api for the store items like this https://store.djangogirls.org/collections/frontpage
3. Implementing a rest api for blog post creation 

Recap for members of the backend team
1 implementation: @wolejnr @adekoder 
2 implementation: @teenoh @Olamyy 
3 implementation: @Cimmanuel @jattoabdul 

I expect dedicated issues to be raised on the individual implementation if more clarification is needed.

I would be setting up the django repo on the `develop` branch before the end of the day.

Implementing the Rest api as a graphql endpoint would make work on the frontend alot easier.

**Comment by gbozee** [comment]
Since React is the framework of choice for the frontend, We would be making use of gatsbyJS as the static site framework of choice.

Once the designs are available work would start immediately.

I would be working mostly on devops/infrastructure as well as code review and providing assistance on implementation where needed.

I would also ensure that a staging version of the site on every pull request merged is available.

So i would be closing this issue now.

**Comment by Olamyy** [comment]
Hi @gbozee , Have we agreed on the model fields for users and store items discussed https://github.com/pyung/Python-Nigeria-Community-Site/issues/11#issuecomment-354157210 ?

My branch currently has the following fields setup for a product.

- product_code

- unit_price

- image

- details


For the user models, I have 
- username
- email

as fields.

Can I go ahead with those?

**Comment by gbozee** [comment]
Yeah @Olamyy it would be nice if a dedicated issue is created for this? so that it would be easier to follow for other members? Please repost the question as a new issue. You call the issue **Implementation details for Store items**

**Comment by gbozee** [comment]
In the issue, you can invite your team member along with me to begin discussions around it.
