### ISSUE TITLE
need a join page

### ISSUE THREAD

**Issue by buddiex** [pyung/pyung.github.io#7]
for now as a quick fix, can we have the join button link to the join-us section of the home page where the 3 methods to join are?
In the long run we will need a join page so that the link http://pythonnigeria.org/joinus/ can be avaliable. we can send to anyone who wishes to join the community.
the avenues to join will be available with explanation of what the different avenues to join is about and the rules we adhere to.
we currently have them at the bottom of the home page.

**Comment by shante665** [comment]
So what we need on a Joinus link would be, a link to join us on Slack, another link to be signed up to the mailing list automatically, and what would be the third one? to register on the site with email address

**Comment by ghost** [comment]
@b33sama,

Please take note of this and help us implement it. Thanks.


*iChux*™
https://ng.linkedin.com/in/ichux
http://stackoverflow.com/story/nwaomachux
<http://stackoverflow.com/users/2787992/ichux>

*Behind every no entry sign, there is a door.*

**Comment by gbozee** [comment]
Would something like this be a good idea?
![image](https://cloud.githubusercontent.com/assets/1777544/20661089/27a7a8e8-b54d-11e6-903d-cc31e259f974.png)

or should i stack it vertically instead?

**Comment by buddiex** [comment]
Yes this is OK.

**Comment by buddiex** [comment]
@shan

**Comment by takwas** [comment]
Please use an "AND" instead of the "OR".

Thanks.
