### ISSUE TITLE
A Profiling form Information For the Slack Invite

### ISSUE THREAD

**Issue by shante665** [pyung/pyung.github.io#8]
On our Heroku App for the slack invite can we include more fields that intending members must compulsorily fill before Joining instead of only Emails. It would be valuable to profile members of the community. 

- Name
-Occupation
- What do you do with Python
- For How Long have you used Python
-Other Python Interests

**Comment by gbozee** [comment]
The problem with the above is where we would be storing this data. Also just asking but what do we plan to use this data for above if we were to collect it?

**Comment by shante665** [comment]
Isn't there a way to get a free MySql database. So the plan majorly is whenever there was a need to reach out to some specific individuals in the community. Having relevant data about our members will help in knowing who to reach out to

**Comment by Insaida** [comment]
I know this is closed, but how about we collect this info through the welcome bot we talked about? So when welcoming new users, the bot asks for this info via DM. Would be nicer and more interactive.

**Comment by gbozee** [comment]
It would be better to create a new issue for what you are requesting.
